---
heat_template_version: 2016-04-08

description:
  Security groups

parameters:

resources:

  common-secgrp:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Common security group for Servers in VPC
      rules:
        - {"direction": "ingress", "remote_mode": "remote_group_id"}
        - {"protocol": "icmp", "direction": "ingress"}
        - {"protocol": "tcp",  "direction": "ingress", "port_range_min": 22, "port_range_max": 22}


outputs:
  common-secgrp:
    description: Common security group
    value: { get_resource: common-secgrp }
