---
# Heat stack with VPC, serverServer, AWX

heat_template_version: 2016-04-08

description:
  Example template

parameters:

  prefix:
    type: string
    description: Prefix for naming resources
    default: test-

  # Connectivity
  external_network:
    type: string
    description: >
      The external network that provides floating IP addresses for the nodes
    default: admin_external_net
    constraints:
    - custom_constraint: neutron.network

  subnet_cidr:
    type: string
    description: CIDR for the default subnetwork in the VPC
    default: 192.168.110.0/24

  dns_nameservers:
    type: comma_delimited_list
    description: Default DNS servers in the VPC
    default: ['100.125.4.25', '8.8.8.8']

  domain_name:
    type: string
    description: >
      Domain name for instances
    default: test.com

  server_flavor:
    type: string
    description: >
      Flavor for the server server
    default: s2.large.1
    constraints:
      - custom_constraint: nova.flavor

  server_image:
    type: string
    description: >
      Image for the server server
    default: Standard_Fedora_29_latest
    constraints:
      - custom_constraint: glance.image

  server_keypair_name:
    type: string
    description: >
      KeyPair for the server server
    hidden: True
    constraints:
      - custom_constraint: nova.keypair

  server_root_volume_size:
    type: number
    description: >
      Size of the root partition for server server
    default: 10
    constraints:

  server_ssh_user:
    type: string
    description: >
      SSH user for the connection to the server
    default: linux

  config_repo:
    type: string
    description: git repo of the configuration (will be polled periodically)
    default: "https://github.com/opentelekomcloud-infra/ansible-zuul"

  common_role_name:
    type: string
    description: Galaxy role to be applied to each server
    default: opentelekomcloud.server_common

resources:

  vpc:
    type: Heat::OTC::VPC
    properties:
      prefix: { get_param: prefix }
      external_network: { get_param: external_network }
      dns_nameservers: { get_param: dns_nameservers }
      subnet_cidr: { get_param: subnet_cidr }

  sg:
    type: sec_grp.yaml

  server:
    type: server.yaml
    properties:
      hostname: server
      domain_name: { get_param: domain_name }
      network: { get_attr: [vpc, network] }
      subnet: { get_attr: [vpc, subnet] }
      image: { get_param: server_image }
      flavor: { get_param: server_flavor }
      keypair_name: { get_param: server_keypair_name }
      root_volume_size: { get_param: server_root_volume_size }
      security_groups:
        - { get_attr: [sg, common-secgrp] }
      metadata:
        groups:
          - server
          - { get_param: domain_name }
        host-type: server
        sub-host-type: server
        ansible_user: { get_param: server_ssh_user }
      common_role_name: { get_param: common_role_name }
      config_repo: { get_param: config_repo }

outputs:
  server:
    description: Server information
    value: { get_attr: [ server ] }
